### ISSUE TITLE
support mmdebstrap's `--format` option

### ISSUE THREAD

**Issue by Infinoid** [bdrung/bdebstrap#4]
Hi,

I like the idea of bdebstrap, so I tried it out today.  However, it doesn't seem to capture my usage of mmdebstrap.

I tried to put my mmdebstrap parameters into a yaml format and run it with bdebstrap, and found that the --format parameter is not supported as a yaml key.  I tried this input:

```yaml
---
mmdebstrap:
  architectures:
    - arm64
  suite: bookworm
  target: tmp/root.ext2
  format: ext2
  variant: minbase
  mode: unshare
  packages:
    - openssh-server
    - netplan.io
    - libpam-systemd
```

And I got this output:

```
2022-11-05 14:29:14,223 bdebstrap WARNING: Ignoring unknown mmdebstrap option 'format'.
```

The parameter exists, and it works when I run mmdebstrap directly.  Here's the [mmdebstrap documentation](https://manpages.debian.org/testing/mmdebstrap/mmdebstrap.1.en.html#format).  Is it possible for bdebstrap to pass it through somehow?

I was expecting it to run something similar to this:
```
mmdebstrap --architectures=arm64 --variant=minbase --format=ext2 --mode=unshare --include=openssh-server,netplan.io,libpam-systemd bookworm tmp/root.ext2
```

Thanks!
